include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**.g.dart"
    - "**.mocks.dart"
    - "lib/generated_plugin_registrant.dart"
  plugins:
    - dart_code_metrics


