#!/usr/bin/env python3
"""Detect unused AppLocalizations translation keys.

A key is considered "used" when it appears in the Dart codebase (lib/ and test/)
through one of the supported access patterns:

  - AppLocalizations.of(context)!.KEY            (possibly multi-line, optional `!`)
  - AppLocalizations.of(context)!.KEY(...)        (method-style calls with placeholders)
  - variable aliases bound to AppLocalizations.of(...), e.g.
        final localizations = AppLocalizations.of(context)!;
        ... localizations.KEY / localizations!.KEY

Keys that are only referenced by their `@key` metadata (or by plural sub-variants
such as `KEYOther` / `KEYOne`) and never invoked from code are reported as unused.

Usage:
    python3 scripts/check_unused_translations.py [arb_dir] [--fix]

Without --fix, prints the unused keys per ARB file and exits with code 1 if any
are found. With --fix, the unused keys (and their `@key` metadata) are removed
in-place from every ARB file.

The ARB directory defaults to `lib/l10n` (relative to the repo root, which is
the parent directory of this `scripts/` folder).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


# Files / directories to scan for key usages.
SCAN_DIRS = ["lib", "test"]
# Files generated by `flutter gen-l10n` -- never scan them for usage evidence.
IGNORED_FILES = {
    "lib/l10n/app_localizations.dart",
    "lib/l10n/app_localizations_en.dart",
    "lib/l10n/app_localizations_fr.dart",
    "lib/l10n/app_localizations_es.dart",
}

# Matches `AppLocalizations.of(<anything>)!?KEY`, tolerating newlines/whitespace
# between `of(`, the argument, `)` and the optional `!`. The KEY is captured.
DIRECT_RE = re.compile(
    r"AppLocalizations\.of\(\s*[^)]*?\)\s*!?\s*\.\s*([A-Za-z][A-Za-z0-9_]*)"
)
# Matches `<alias>.KEY` / `<alias>!.KEY` where alias is an identifier that was
# assigned from `AppLocalizations.of(...)`.
ALIAS_DECL_RE = re.compile(
    r"\b(?:final|var)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*AppLocalizations\.of\("
)


def collect_used_keys(repo_root: Path) -> set[str]:
    """Return the set of localization keys referenced from Dart source."""
    used: set[str] = set()

    for scan_dir in SCAN_DIRS:
        base = repo_root / scan_dir
        if not base.exists():
            continue
        for dart_file in base.rglob("*.dart"):
            rel = dart_file.relative_to(repo_root).as_posix()
            if rel in IGNORED_FILES:
                continue
            try:
                text = dart_file.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue

            # 1. Direct calls: AppLocalizations.of(context)!.KEY
            for key in DIRECT_RE.findall(text):
                used.add(key)

            # 2. Variable aliases: capture alias names, then find <alias>.KEY.
            for alias in ALIAS_DECL_RE.findall(text):
                alias_re = re.compile(
                    rf"\b{re.escape(alias)}\s*!?\s*\.\s*([A-Za-z][A-Za-z0-9_]*)"
                )
                for key in alias_re.findall(text):
                    used.add(key)

    return used


def arb_keys(arb_path: Path) -> list[str]:
    """Return the user-facing keys (excluding `@key` metadata), in file order."""
    data = json.loads(arb_path.read_text(encoding="utf-8"))
    return [k for k in data.keys() if not k.startswith("@")]


def find_unused(arb_path: Path, used: set[str]) -> list[str]:
    unused: list[str] = []
    for key in arb_keys(arb_path):
        # A key is "used" if it or any of its plural sub-variants
        # (KEYOne, KEYOther, KEYFew, KEYMany, KEYZero, KEYTwo) is referenced.
        variants = {key} | {
            f"{key}{suffix}"
            for suffix in ("Zero", "One", "Two", "Few", "Many", "Other")
        }
        if variants.isdisjoint(used):
            unused.append(key)
    return unused


def remove_keys(arb_path: Path, keys: set[str]) -> None:
    data: dict = json.loads(arb_path.read_text(encoding="utf-8"))
    for key in list(keys):
        data.pop(key, None)
        data.pop(f"@{key}", None)
    # 2-space indentation, preserve a trailing newline to match Flutter style.
    arb_path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "arb_dir",
        nargs="?",
        default="lib/l10n",
        help="Directory containing the app_*.arb files (default: lib/l10n).",
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help="Remove the unused keys (and their @metadata) from the ARB files.",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    arb_dir = (repo_root / args.arb_dir).resolve()
    if not arb_dir.is_dir():
        print(f"error: ARB directory not found: {arb_dir}", file=sys.stderr)
        return 2

    arb_files = sorted(arb_dir.glob("app_*.arb"))
    if not arb_files:
        print(f"error: no app_*.arb files in {arb_dir}", file=sys.stderr)
        return 2

    used = collect_used_keys(repo_root)
    print(f"Scanned Dart sources and found {len(used)} distinct referenced keys.\n")

    total_unused = 0
    per_file: dict[Path, list[str]] = {}
    for arb in arb_files:
        unused = find_unused(arb, used)
        per_file[arb] = unused
        total_unused += len(unused)
        print(f"{arb.relative_to(repo_root)}: {len(unused)} unused key(s)")
        for k in unused:
            print(f"  - {k}")
        print()

    if total_unused == 0:
        print("No unused translation keys found.")
        return 0

    if args.fix:
        for arb, unused in per_file.items():
            if unused:
                remove_keys(arb, set(unused))
                print(f"Removed {len(unused)} unused key(s) from "
                      f"{arb.relative_to(repo_root)}")
        print(f"\nDone: removed {total_unused} unused key(s) in total.")
        return 0

    print(f"{total_unused} unused key(s) found across all ARB files.")
    print("Re-run with --fix to remove them.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
