name: Fastlane

on:
  workflow_call:
    inputs:
      lane:
        description: 'Lane version (alpha, beta, or production)'
        required: true
        type: string

jobs:
  play_store:
    environment:
      name: Fastlane ${{ inputs.lane }} lane
      url: 'https://play.google.com/console/u/0/developers/5699287307345981322/app/4972786398063514472/releases/overview'
    name: 'Play Store'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: 'Check secret configuration'
        run: ./.github/scripts/check_secrets_decryption.sh
      - name: 'Download Artifact'
        uses: actions/download-artifact@v4
        with:
          name: 'aab-build'
      - name: 'Setup Ruby'
        uses: ruby/setup-ruby@v1.174.0
        with:
          ruby-version: '3.0'
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: 'android/Gemfile'
      - name: 'Fastlane deploy ${{ inputs.lane }} lane'
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: ${{ inputs.lane }}
          subdirectory: 'android'
        env:
          SUPPLY_UPLOAD_MAX_RETRIES: 5
