name: Action - Release

on:
  workflow_call:
    inputs:
      is_a_prerelease:
        description: 'Specify if this need to be tagged as a pre-release version'
        required: true
        type: boolean

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: 'Craft the Changelog'
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: "Generate CHANGELOG.md"
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          onlyLastTag: true
      - name: 'Upload CHANGELOG.md'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: changelog
          path: CHANGELOG.md
  release:
    runs-on: ubuntu-latest
    name: 'Publish the Release'
    needs: [ changelog ]
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: 'Download binary artifacts'
        uses: actions/download-artifact@v4.1.9
        with:
          name: 'aab-build'
      - name: 'Download CHANGELOG artifacts'
        uses: actions/download-artifact@v4.1.9
        with:
          name: changelog
      - name: 'Generate Github release'
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ inputs.is_a_prerelease }}
          name: '${{ github.ref_name }} 🚀'
          body_path: CHANGELOG.md
          files: |
            *.aab
