name: Dev workflow

on:
  push:
    branches:
      - dev

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/flutter.analyze-test.action.yaml
    with:
      flutter_version: '3.19.3'
    secrets: inherit
  page:
    uses: ./.github/workflows/pages.deploy.yaml
  flutter-build:
    needs: [flutter-test-analyze]
    uses: ./.github/workflows/flutter.build.action.yaml
    with:
      flutter_version: '3.19.3'
      android_output: 'aab'
      env: 'dev'
    secrets: inherit
  fastlane-dry-run:
    needs: [ flutter-build ]
    uses: ./.github/workflows/fastlane.action.yaml
    with:
      lane: 'dry_run'
    secrets: inherit
