name: Flutter - Build

on:
  workflow_call:
    inputs:
      flutter_version:
        description: 'The Flutter used (ex: 2.5.1)'
        required: true
        type: string
      android_output:
        description: 'Android build file type output (apk or abb)'
        required: true
        type: string
    secrets:
      passphrase:
        description: 'The passphrase to decrypt the configuration'
        required: true


jobs:
  build_android:
    name: 'Android (${{ inputs.android_output }})'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3.4.0
        with:
          fetch-depth: 0
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.passphrase }}
      - name: 'Check secret configuration'
        run: ./.github/scripts/check_secrets_decryption.sh
      - name: 'Set up JAVA'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ inputs.flutter_version }}
      - name: 'Build Android APK'
        if: ${{ inputs.android_output == 'apk' }}
        # Build APK version of the app
        run: flutter build apk --split-per-abi
      - name: 'Save APK'
        if: ${{ inputs.android_output == 'apk' }}
        uses: actions/upload-artifact@v3
        with:
          name: 'apk-build'
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
      - name: 'Generate build number'
        if: ${{ inputs.android_output == 'aab' }}
        # Build App Bundle version of the app
        run: |
          BUILD_NUMBER=$(git rev-list --all --count)
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "This build is tagged as $BUILD_NUMBER on $GITHUB_REF"
      - name: 'Build Android App Bundle'
        if: ${{ inputs.android_output == 'aab' }}
        run: flutter build appbundle --dart-define=FLAVOR=prod --build-number="$BUILD_NUMBER"
        env:
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
      - name: 'Save AAB'
        if: ${{ inputs.android_output == 'aab' }}
        uses: actions/upload-artifact@v3
        with:
          name: 'aab-build'
          path: build/app/outputs/bundle/release/app-release.aab
  build_ios:
    name: 'iOS'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.passphrase }}
      - name: 'Check secret configuration'
        run: ./.github/scripts/check_secrets_decryption.sh
      - name: '🥺'
        run: echo 'WIP'
  build_web:
    name: 'WEB'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.passphrase }}
      - name: 'Check secret configuration'
        run: ./.github/scripts/check_secrets_decryption.sh
      - name: '🥺'
        run: echo 'WIP'