name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/flutter.analyze-test.action.yaml
    with:
      flutter_version: '3.13.9'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
  flutter-build:
    needs: [flutter-test-analyze]
    uses: ./.github/workflows/flutter.build.action.yaml
    with:
      flutter_version: '3.13.9'
      android_output: 'aab'
      env: 'prd'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
      sentry_dsn: ${{ secrets.SENTRY_DSN }}
  fastlane:
    needs: [flutter-build]
    uses: ./.github/workflows/fastlane.action.yaml
    with:
      lane: 'prd'
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}
