name: Default workflow

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/action.flutter.analyze-test.yaml
    with:
      flutter_version: '3.19.3'
    secrets: inherit
  flutter-build:
    needs: [ flutter-test-analyze ]
    uses: ./.github/workflows/action.flutter.build.yaml
    with:
      flutter_version: '3.19.3'
      android_output: 'apk'
      env: 'dev'
    secrets: inherit
