name: Beta Tag workflow

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-beta'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter-build:
    uses: ./.github/workflows/action.flutter.build.yaml
    with:
      flutter_version: '3.32.2'
      android_output: 'aab'
      env: 'beta'
    secrets: inherit
  release:
    needs: [ flutter-build ]
    uses: ./.github/workflows/action.release.yaml
    with:
      is_a_prerelease: true
  fastlane:
    needs: [ flutter-build ]
    uses: ./.github/workflows/action.fastlane.yaml
    with:
      lane: 'beta'
    secrets: inherit
