name: Dev workflow

on:
  push:
    branches:
      - dev

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/action.flutter.analyze-test.yaml
    with:
      flutter_version: '3.19.3'
    secrets: inherit
  page:
    uses: ./.github/workflows/action.pages.deploy.yaml
  flutter-build:
    needs: [ flutter-test-analyze ]
    uses: ./.github/workflows/action.flutter.build.yaml
    with:
      flutter_version: '3.19.3'
      android_output: 'aab'
      env: 'dev'
    secrets: inherit
  fastlane-dry-run:
    needs: [ flutter-build ]
    uses: ./.github/workflows/action.fastlane.yaml
    with:
      lane: 'dry_run'
    secrets: inherit
