name: Workflow - Lint, Test, Build and Publish Flutter project

on:
  push:


concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter-analyze:
    uses: vareversat/github-actions/.github/workflows/flutter.analyze.yml@v1.2.3
    with:
      flutter_version: '3.19.3'
  flutter-format:
    uses: vareversat/github-actions/.github/workflows/flutter.format.yml@v1.2.3
    with:
      flutter_version: '3.19.3'
  flutter-test:
    uses: vareversat/github-actions/.github/workflows/flutter.test.yml@v1.2.3
    secrets: inherit
    with:
      flutter_version: '3.19.3'
  build-type:
    runs-on: ubuntu-latest
    outputs:
      build_apk: ${{ steps.compute.outputs.BUILD_APK }}
      build_aab: ${{ steps.compute.outputs.BUILD_AAB }}
    steps:
      - name: 'Get the correct Android build type'
        id: compute 
        run: |
          if [ ${{ github.ref }} = "refs/heads/main" ]; then
            echo "BUILD_APK=false" >> $GITHUB_OUTPUT
            echo "BUILD_AAB=true" >> $GITHUB_OUTPUT
          else
            echo "BUILD_APK=true" >> $GITHUB_OUTPUT
            echo "BUILD_AAB=false" >> $GITHUB_OUTPUT
          fi
  page:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: vareversat/github-actions/.github/workflows/global.page.yml@v1.2.3
    with:
      path: page
  flutter-build:
    needs: [ flutter-analyze, flutter-format, flutter-test, build-type ]
    uses: vareversat/github-actions/.github/workflows/flutter.build.yml@0fed046594b75b8589bf960d759334995eaf5666
    secrets: inherit
    with:
      flutter_version: '3.19.3'
      flutter_flavor: 'dev'
      java_version: '17.x'
      build_android_apk: ${{ needs.build-type.outputs.build_apk }}
      build_android_aab: ${{ needs.build-type.outputs.build_aab }}
  flutter-publish:
    needs: [ flutter-build ]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: vareversat/github-actions/.github/workflows/flutter.publish.yml@v1.2.3
    secrets: inherit
    with:
      lane: 'dry_run'
      url: 'https://play.google.com/console/u/0/developers/5699287307345981322/app/4972786398063514472/releases/overview'