name: Workflow - Publish project release

on:
  push:
    tags:
      - v*

concurrency:
  group: ci-${{ github.ref }}-tag
  cancel-in-progress: true

jobs:
  release-info:
    uses: vareversat/github-actions/.github/workflows/global.release.info.yml@v1.6.2
    with:
      revision_type: 'date'

  flutter-build:
    uses: vareversat/github-actions/.github/workflows/flutter.build.yml@v1.6.2
    needs: [ release-info ]
    with:
      flutter_version: '3.32.2'
      flutter_flavor: 'prod'
      java_version: '17.x'
      build_android_aab: 'true'
      build_name: ${{ needs.release-info.outputs.version_name }}
      build_number: ${{ needs.release-info.outputs.revision_name }}
    secrets: inherit

  fastlane-lane:
    uses: vareversat/github-actions/.github/workflows/fastlane.lane.yml@v1.6.2
    with:
      prerelease_suffix: 'beta'
  page-publish:
    uses: vareversat/github-actions/.github/workflows/global.page.yml@v1.6.2
    with:
      path: 'page'
  flutter-publish:
    needs: [ flutter-build, fastlane-lane ]
    uses: vareversat/github-actions/.github/workflows/flutter.publish.yml@v1.6.2
    with:
      lane: ${{ needs.fastlane-lane.outputs.lane }}
      url: 'https://play.google.com/console/u/0/developers/5699287307345981322/app/4972786398063514472/app-dashboard'
    secrets: inherit

  release:
    needs: [ flutter-publish ]
    uses: vareversat/github-actions/.github/workflows/global.release.yml@v1.6.2
    with:
      prerelease_suffix: 'beta'
