name: Tag workflow

on:
  push:
    tags:
      - v*

jobs:
  flutter-test-analyze:
    uses: ./.github/workflows/flutter.analyze-test.action.yaml
    with:
      flutter_version: '3.19.3'
    secrets: inherit
  flutter-build:
    needs: [flutter-test-analyze]
    uses: ./.github/workflows/flutter.build.action.yaml
    with:
      flutter_version: '3.19.3'
      android_output: 'aab'
      env: 'beta'
    secrets: inherit
  fastlane:
    needs: [flutter-build]
    uses: ./.github/workflows/fastlane.action.yaml
    with:
      lane: 'beta'
    secrets: inherit
